Repository Tave-Makers/SURF-BE, pull requests merged in 2025-09, with the labels that each got.

#6 [Deploy] CICD 파이프라인 추가
  .github/workflows/dev.yml
  Dockerfile-dev
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
Labels: 🌏 Deploy, 👨‍💻 우석

#12 Docs/#10/coderabbit 설정파일 변경
  .coderabbit.yaml
  docs/code-convention.md
Labels: 📃 Docs, 🐈 혜승

#13 Fix/#7/kakaologin 예외처리 리팩토링
  .gitignore
  src/main/java/com/tavemakers/surf/SurfApplication.java
  src/main/java/com/tavemakers/surf/domain/login/AuthService.java
  src/main/java/com/tavemakers/surf/domain/login/LoginResDto.java
  src/main/java/com/tavemakers/surf/domain/login/kakao/config/KakaoOAuthProps.java
  src/main/java/com/tavemakers/surf/domain/login/kakao/config/RestClientConfig.java
  src/main/java/com/tavemakers/surf/domain/login/kakao/config/SecurityConfig.java
  src/main/java/com/tavemakers/surf/domain/login/kakao/dto/KakaoTokenResponseDto.java
  src/main/java/com/tavemakers/surf/domain/login/kakao/dto/KakaoUserInfoDto.java
  src/main/java/com/tavemakers/surf/domain/login/kakao/service/KakaoAuthServiceImpl.java
  src/main/java/com/tavemakers/surf/domain/member/controller/AuthController.java
  src/main/java/com/tavemakers/surf/kakao/config/KakaoOAuthProps.java
  src/main/java/com/tavemakers/surf/kakao/controller/KakaoAuthController.java
  src/main/java/com/tavemakers/surf/kakao/dto/KakaoTokenResponseDto.java
  src/main/java/com/tavemakers/surf/kakao/service/KakaoAuthService.java
  src/main/java/com/tavemakers/surf/kakao/service/KakaoAuthServiceImpl.java
  src/main/resources/application-local.yml
Labels: 🔨 Refactor, 👨‍💻 동규

#26 [Hotfix] 코드래빗 문서 수정
  .coderabbit.yaml
Labels: 🐞 Bug, 🐈 혜승

#33 [HOTFIX]: 카카오 프로필 정보 누락 해결 #32
  src/main/java/com/tavemakers/surf/domain/login/kakao/service/KakaoAuthServiceImpl.java
Labels: 🐞 Bug, 👨‍💻 동규

#31 [Feat] 활동 뱃지 부여 및 조회
  src/main/java/com/tavemakers/surf/domain/badge/controller/MemberBadgeController.java
  src/main/java/com/tavemakers/surf/domain/badge/controller/ResponseMessage.java
  src/main/java/com/tavemakers/surf/domain/badge/dto/request/MemberBadgeReqDTO.java
  src/main/java/com/tavemakers/surf/domain/badge/dto/response/MemberBadgeResDTO.java
  src/main/java/com/tavemakers/surf/domain/badge/dto/response/MemberBadgeSliceResDTO.java
  src/main/java/com/tavemakers/surf/domain/badge/entity/Badge.java
  src/main/java/com/tavemakers/surf/domain/badge/entity/BadgeType.java
  src/main/java/com/tavemakers/surf/domain/badge/entity/MemberBadge.java
  src/main/java/com/tavemakers/surf/domain/badge/repository/MemberBadgeRepository.java
  src/main/java/com/tavemakers/surf/domain/badge/service/MemberBadgeGetService.java
  src/main/java/com/tavemakers/surf/domain/badge/service/MemberBadgeSaveService.java
  src/main/java/com/tavemakers/surf/domain/badge/usecase/MemberBadgeUsecase.java
  src/main/java/com/tavemakers/surf/domain/member/entity/Badge.java
  src/main/java/com/tavemakers/surf/domain/member/entity/MemberBadge.java
Labels: ✨ Feature, 👨‍💻 우석

#46 [Refact] 전체 회원 조회시 최신 트랙 가져오기 + 스웨거 JWT 설정 추가
  src/main/java/com/tavemakers/surf/domain/login/kakao/config/SecurityConfig.java
  src/main/java/com/tavemakers/surf/domain/member/controller/ResponseMessage.java
  src/main/java/com/tavemakers/surf/domain/member/repository/TrackRepository.java
  src/main/java/com/tavemakers/surf/domain/member/usecase/MemberUsecase.java
  src/main/java/com/tavemakers/surf/global/config/SwaggerConfig.java
Labels: 🔨 Refactor, 🌼 혜승

#37 [Feat] 회원가입
  build.gradle.kts
  src/main/java/com/tavemakers/surf/domain/login/LoginResDto.java
  src/main/java/com/tavemakers/surf/domain/member/controller/AuthController.java
  src/main/java/com/tavemakers/surf/domain/member/controller/MemberController.java
  src/main/java/com/tavemakers/surf/domain/member/dto/request/MemberSignupReqDTO.java
  src/main/java/com/tavemakers/surf/domain/member/dto/response/MemberSignupResDTO.java
  src/main/java/com/tavemakers/surf/domain/member/entity/CustomUserDetails.java
  src/main/java/com/tavemakers/surf/domain/member/entity/Member.java
  src/main/java/com/tavemakers/surf/domain/member/exception/ErrorMessage.java
  src/main/java/com/tavemakers/surf/domain/member/exception/InvalidMemberInfoException.java
  src/main/java/com/tavemakers/surf/domain/member/exception/MemberAlreadyExistsException.java
  src/main/java/com/tavemakers/surf/domain/member/facade/MemberFacade.java
  src/main/java/com/tavemakers/surf/domain/member/repository/MemberRepository.java
  src/main/java/com/tavemakers/surf/domain/member/service/CustomUserDetailsService.java
  src/main/java/com/tavemakers/surf/domain/member/service/MemberService.java
  src/main/java/com/tavemakers/surf/domain/member/service/MemberServiceImpl.java
  src/main/java/com/tavemakers/surf/global/config/SecurityConfig.java
Labels: ✨ Feature, 👨‍💻 동규

#60 [hotfix] SecurityConfig_경로수정
  src/main/java/com/tavemakers/surf/domain/login/kakao/config/SecurityConfig.java
  src/main/java/com/tavemakers/surf/global/config/SecurityConfig.java
Labels: 🐞 Bug, 🌼 혜승

#57 [Feat] 프로필 수정
  .gitignore
  src/main/java/com/tavemakers/surf/domain/member/controller/AuthController.java
  src/main/java/com/tavemakers/surf/domain/member/controller/MemberController.java
  src/main/java/com/tavemakers/surf/domain/member/controller/MemberPatchController.java
  src/main/java/com/tavemakers/surf/domain/member/controller/ResponseMessage.java
  src/main/java/com/tavemakers/surf/domain/member/dto/request/CareerCreateReqDTO.java
  src/main/java/com/tavemakers/surf/domain/member/dto/request/CareerUpdateReqDTO.java
  src/main/java/com/tavemakers/surf/domain/member/dto/request/MemberSignupReqDTO.java
  src/main/java/com/tavemakers/surf/domain/member/dto/request/ProfileUpdateReqDTO.java
  src/main/java/com/tavemakers/surf/domain/member/entity/Career.java
  src/main/java/com/tavemakers/surf/domain/member/entity/Member.java
  src/main/java/com/tavemakers/surf/domain/member/exception/CareerNotFoundException.java
  src/main/java/com/tavemakers/surf/domain/member/exception/ErrorMessage.java
  src/main/java/com/tavemakers/surf/domain/member/facade/MemberFacade.java
  src/main/java/com/tavemakers/surf/domain/member/repository/CareerRepository.java
  src/main/java/com/tavemakers/surf/domain/member/repository/MemberRepository.java
  src/main/java/com/tavemakers/surf/domain/member/service/CareerDeleteService.java
  src/main/java/com/tavemakers/surf/domain/member/service/CareerPatchService.java
  src/main/java/com/tavemakers/surf/domain/member/service/CareerPostService.java
  src/main/java/com/tavemakers/surf/domain/member/service/MemberGetService.java
  src/main/java/com/tavemakers/surf/domain/member/service/MemberPatchService.java
  src/main/java/com/tavemakers/surf/domain/member/service/MemberService.java
  src/main/java/com/tavemakers/surf/domain/member/service/MemberServiceImpl.java
  src/main/java/com/tavemakers/surf/domain/member/service/MemberUpsertService.java
  src/main/java/com/tavemakers/surf/domain/member/usecase/MemberUsecase.java
  src/main/java/com/tavemakers/surf/domain/member/validator/CareerValidator.java
  src/main/java/com/tavemakers/surf/global/config/SecurityConfig.java
  src/main/java/com/tavemakers/surf/global/jwt/JwtAuthenticationFilter.java
  src/main/java/com/tavemakers/surf/global/util/SecurityUtils.java
  src/main/resources/application.yml
Labels: ✨ Feature, 🌼 혜승

#66 [hotfix] 머지 충돌 해결
  src/main/java/com/tavemakers/surf/domain/member/entity/Member.java
  src/main/java/com/tavemakers/surf/domain/member/service/MemberServiceImpl.java
Labels: 🐞 Bug, 🌼 혜승

#77 [Hotfix] Redis Properties 환경변수로 분리
  src/main/resources/application.yml
Labels: 🐞 Bug, 👨‍💻 우석

#78 [Feat] 나의 프로필 조회 시 경력 추가
  src/main/java/com/tavemakers/surf/domain/member/dto/request/CareerCreateReqDTO.java
  src/main/java/com/tavemakers/surf/domain/member/dto/response/CareerResDTO.java
  src/main/java/com/tavemakers/surf/domain/member/dto/response/MyPageProfileResDTO.java
  src/main/java/com/tavemakers/surf/domain/member/entity/Career.java
  src/main/java/com/tavemakers/surf/domain/member/repository/CareerRepository.java
  src/main/java/com/tavemakers/surf/domain/member/service/CareerGetService.java
  src/main/java/com/tavemakers/surf/domain/member/usecase/MemberUsecase.java
Labels: ✨ Feature, 👨‍💻 우석

#73 [Refactor] 스웨거 정리 및 반환 타입 통일
  src/main/java/com/tavemakers/surf/domain/board/controller/BoardController.java
  src/main/java/com/tavemakers/surf/domain/board/controller/ResponseMessage.java
  src/main/java/com/tavemakers/surf/domain/board/dto/req/BoardCreateReqDTO.java
  src/main/java/com/tavemakers/surf/domain/board/dto/req/BoardUpdateReqDTO.java
  src/main/java/com/tavemakers/surf/domain/board/dto/res/BoardResDTO.java
  src/main/java/com/tavemakers/surf/domain/feedback/controller/FeedbackController.java
  src/main/java/com/tavemakers/surf/domain/feedback/controller/ResponseMessage.java
  src/main/java/com/tavemakers/surf/domain/feedback/dto/req/FeedbackCreateReqDTO.java
  src/main/java/com/tavemakers/surf/domain/feedback/dto/res/FeedbackResDTO.java
  src/main/java/com/tavemakers/surf/domain/post/controller/PostController.java
  src/main/java/com/tavemakers/surf/domain/post/controller/ResponseMessage.java
  src/main/java/com/tavemakers/surf/domain/post/dto/req/PostCreateReqDTO.java
  src/main/java/com/tavemakers/surf/domain/post/dto/req/PostUpdateReqDTO.java
  src/main/java/com/tavemakers/surf/domain/post/dto/res/PostResDTO.java
  src/main/java/com/tavemakers/surf/domain/post/entity/Post.java
  src/main/java/com/tavemakers/surf/domain/scrap/controller/ResponseMessage.java
  src/main/java/com/tavemakers/surf/domain/scrap/controller/ScrapController.java
Labels: 🔨 Refactor, 👨‍💻 성현

#82 [Docs] 권한 부여 API + 전체적인 URL 통일 및 수정
  src/main/java/com/tavemakers/surf/domain/activity/controller/ActivityRecordController.java
  src/main/java/com/tavemakers/surf/domain/badge/controller/MemberBadgeController.java
  src/main/java/com/tavemakers/surf/domain/board/controller/BoardController.java
  src/main/java/com/tavemakers/surf/domain/feedback/controller/FeedbackController.java
  src/main/java/com/tavemakers/surf/domain/member/controller/AdminController.java
  src/main/java/com/tavemakers/surf/domain/member/controller/MemberController.java
  src/main/java/com/tavemakers/surf/domain/member/controller/MemberPatchController.java
  src/main/java/com/tavemakers/surf/domain/member/controller/MemberSearchController.java
  src/main/java/com/tavemakers/surf/domain/member/dto/request/RoleChangeRequestDto.java
  src/main/java/com/tavemakers/surf/domain/member/entity/Member.java
  src/main/java/com/tavemakers/surf/domain/member/entity/enums/MemberRole.java
  src/main/java/com/tavemakers/surf/domain/member/service/MemberPatchService.java
  src/main/java/com/tavemakers/surf/domain/member/usecase/MemberAdminUsecase.java
  src/main/java/com/tavemakers/surf/domain/post/controller/PostController.java
  src/main/java/com/tavemakers/surf/domain/score/controller/PersonalScoreController.java
  src/main/java/com/tavemakers/surf/domain/scrap/controller/ScrapController.java
  src/main/java/com/tavemakers/surf/global/config/PermitUrlConfig.java
  src/main/java/com/tavemakers/surf/global/config/SecurityConfig.java
Labels: 🔨 Refactor, 📃 Docs, 🌼 혜승

#87 [Hotfix] CORS 경로 추가
  src/main/java/com/tavemakers/surf/global/config/SecurityConfig.java
Labels: 🐞 Bug, 🌼 혜승

#89 [FEAT][BUG] 여러 버그 및 신기능 추가
  src/main/java/com/tavemakers/surf/domain/member/controller/MemberController.java
  src/main/java/com/tavemakers/surf/domain/member/dto/request/CareerUpdateReqDTO.java
  src/main/java/com/tavemakers/surf/domain/member/dto/request/ProfileUpdateReqDTO.java
  src/main/java/com/tavemakers/surf/domain/member/dto/response/CareerResDTO.java
  src/main/java/com/tavemakers/surf/domain/member/dto/response/MyPageProfileResDTO.java
  src/main/java/com/tavemakers/surf/domain/member/entity/Career.java
  src/main/java/com/tavemakers/surf/domain/member/entity/Member.java
  src/main/java/com/tavemakers/surf/domain/member/service/MemberGetService.java
  src/main/java/com/tavemakers/surf/domain/member/service/MemberService.java
  src/main/java/com/tavemakers/surf/domain/member/service/MemberServiceImpl.java
  src/main/java/com/tavemakers/surf/domain/member/usecase/MemberAdminUsecase.java
  src/main/java/com/tavemakers/surf/domain/member/usecase/MemberUsecase.java
Labels: ✨ Feature, 🐞 Bug, 🌼 혜승

#97 [Feat] 인증객체의 memberId 사용
  src/main/java/com/tavemakers/surf/domain/activity/controller/ActivityRecordController.java
  src/main/java/com/tavemakers/surf/domain/score/controller/PersonalScoreController.java
Labels: ✨ Feature, 🔨 Refactor, 👨‍💻 우석

#105 [Feat] 프로필 조회 Dto에 활동여부 추가
  src/main/java/com/tavemakers/surf/domain/member/dto/response/MyPageProfileResDTO.java
Labels: ✨ Feature, 👨‍💻 우석
